spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        #        QueryDSL로 사용된 JPQL 보기
        use_sql_comments: true
        default_batch_fetch_size: 500 # 컬렉션 조회 페이징 및 최적화
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  datasource:
    app:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://database-1.cirwaade9h96.ap-northeast-2.rds.amazonaws.com/neighbor
      username: postgres
      password: neighbor1572
    log:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://database-1.cirwaade9h96.ap-northeast-2.rds.amazonaws.com/neighbor
      username: postgres
      password: neighbor1572
logging.level:
  org.hibernate.SQL: debug