spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_batch_fetch_size: 500 # 컬렉션 조회 페이징 및 최적화
        dialect: org.hibernate.dialect.PostgreSQLDialect
    #        use_sql_comments: true
    open-in-view: false

  datasource:
    app:
      driver-class-name: org.postgresql.Driver
      url: ENC(0nm38ff3I+x+S+ldXfnqpdZl8Wkaub6tBShSUmYGFv1ii49j7t4bHdJ90rzzXy9LaHHxhQq432pXOHkvaO+py4noCIRudytqHiV70HP/UMlAQog0uEDkRCIu/Bdrsz+Y)
      username: ENC(w+dERMTX+KzzwtHlVxsQKAberPBrzay0)
      password: ENC(LpnoSF8dh1K7eHoI+wS+tDD+KCh/h13F)
    log:
      driver-class-name: org.postgresql.Driver
      url: ENC(0nm38ff3I+x+S+ldXfnqpdZl8Wkaub6tBShSUmYGFv1ii49j7t4bHdJ90rzzXy9LaHHxhQq432pXOHkvaO+py4noCIRudytqHiV70HP/UMlAQog0uEDkRCIu/Bdrsz+Y)
      username: ENC(w+dERMTX+KzzwtHlVxsQKAberPBrzay0)
      password: ENC(LpnoSF8dh1K7eHoI+wS+tDD+KCh/h13F)

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

aes:
  secret-key: ENC(fTa2qwMWVDf6dh0nqBhfE6tGobUjdmvFk0DQux6Ap1xnZW2Ym0R7NCgc2oqU26y0)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    property:
      prefix: ENC(
      suffix: )
